#!/usr/bin/env python3
"""GAMEtime library tool — add, update, and remove games offline.

The source of truth is library.json; every command that changes it also
regenerates data.js, which is what the website reads. Metadata, covers and
time-to-beat hours come from IGDB (api.igdb.com, run by Twitch).

Setup (once):
  1. Register an app at https://dev.twitch.tv/console/apps
     (OAuth redirect http://localhost, client type Confidential)
  2. Save the credentials next to this script in .igdb_auth:
       client_id=YOUR_CLIENT_ID
       client_secret=YOUR_CLIENT_SECRET
     (or export IGDB_CLIENT_ID / IGDB_CLIENT_SECRET)

Usage:
  ./gametime.py add "Chrono Trigger" --score 9.5
  ./gametime.py add "Silksong" --status toplay
  ./gametime.py add "Resident Evil 4" --year 2005 --status playing --progress 6.5
  ./gametime.py update chrono-trigger --score 10      # stamps today's date
  ./gametime.py update "resident evil 4" --year 2023 --score 9   # pick between remakes
  ./gametime.py update silksong --status playing --progress 2
  ./gametime.py remove chrono-trigger
  ./gametime.py list
  ./gametime.py regen        # rebuild data.js from library.json
  ./gametime.py check        # scan the library for duplicate entries

Statuses: playing · toplay · played.  Scoring implies played.
Progress is hours played, e.g. --progress 12.5

No dependencies beyond the standard library.
"""

import argparse
import datetime
import json
import os
import re
import sys
import time
import urllib.parse
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent
LIBRARY_PATH = ROOT / "library.json"
DATA_JS_PATH = ROOT / "data.js"
COVERS_DIR = ROOT / "covers"
AUTH_PATH = ROOT / ".igdb_auth"
TOKEN_CACHE = ROOT / ".igdb_token"

IGDB_API = "https://api.igdb.com/v4"
IGDB_IMG = "https://images.igdb.com/igdb/image/upload/t_cover_big_2x"
TWITCH_TOKEN_URL = "https://id.twitch.tv/oauth2/token"

DATA_JS_HEADER = """\
// GENERATED by gametime.py from library.json — do not edit by hand.
// Edit entries with:  ./gametime.py add|update|remove   (see ./gametime.py --help)

const LIBRARY = """

# IGDB genre names are a mouthful — trim them to chip-sized labels
GENRE_TRIM = {
    "Role-playing (RPG)": "RPG",
    "Turn-based strategy (TBS)": "Strategy",
    "Real Time Strategy (RTS)": "Strategy",
    "Hack and slash/Beat 'em up": "Hack & Slash",
    "Card & Board Game": "Cards",
    "Point-and-click": "Point & Click",
    "Quiz/Trivia": "Quiz",
}


# ---------- library file handling ----------

def load_library():
    if not LIBRARY_PATH.exists():
        return []
    return json.loads(LIBRARY_PATH.read_text(encoding="utf-8"))


def save_library(lib):
    LIBRARY_PATH.write_text(json.dumps(lib, indent=2, ensure_ascii=False) + "\n",
                            encoding="utf-8")
    DATA_JS_PATH.write_text(DATA_JS_HEADER + json.dumps(lib, indent=2, ensure_ascii=False) + ";\n",
                            encoding="utf-8")
    print(f"saved {len(lib)} entries -> library.json + data.js")
    hard, _ = library_duplicates(lib)
    if hard:
        names = "; ".join(" / ".join(f"[{e['id']}]" for e in g) for g in hard)
        print(f"warning: same game added twice: {names}  (run ./gametime.py check)")


def slugify(title):
    slug = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")
    return slug or "untitled"


def unique_slug(lib, title, year=None):
    """Slug from the title. On a collision prefer a year suffix over a bare counter,
    so two games sharing a name stay tellable apart (resident-evil-4-2023, not -2)."""
    base = slugify(title)
    ids = {e["id"] for e in lib}
    if base not in ids:
        return base
    if year and f"{base}-{year}" not in ids:
        return f"{base}-{year}"
    slug, n = base, 2
    while slug in ids:
        slug = f"{base}-{n}"
        n += 1
    return slug


def find_entry(lib, key, year=None):
    """Find by exact id, then by title substring; --year narrows a name collision."""
    pool = [e for e in lib if year is None or e.get("year") == year]
    for e in pool:
        if e["id"] == key:
            return e
    matches = [e for e in pool if key.lower() in e["title"].lower()]
    if len(matches) == 1:
        return matches[0]
    if len(matches) > 1:
        rows = "\n".join(f"  {e['id']:<34} {e['title']} ({e.get('year', '?')}) — {e['status']}"
                         for e in matches)
        sys.exit(f"'{key}' matches {len(matches)} entries — name an id, or pass --year:\n{rows}")
    scope = f" from {year}" if year else ""
    sys.exit(f"no entry matching '{key}'{scope} (try ./gametime.py list)")


# ---------- IGDB auth (Twitch client-credentials, token cached on disk) ----------

def read_credentials():
    cid = os.environ.get("IGDB_CLIENT_ID")
    secret = os.environ.get("IGDB_CLIENT_SECRET")
    if not (cid and secret) and AUTH_PATH.exists():
        kv = {}
        for line in AUTH_PATH.read_text().splitlines():
            if "=" in line:
                k, _, v = line.partition("=")
                kv[k.strip()] = v.strip()
        cid = cid or kv.get("client_id")
        secret = secret or kv.get("client_secret")
    if not (cid and secret):
        sys.exit("no IGDB credentials. Put client_id=… and client_secret=… in .igdb_auth\n"
                 "(register an app at https://dev.twitch.tv/console/apps)")
    return cid, secret


def fetch_token(cid, secret):
    body = urllib.parse.urlencode({
        "client_id": cid, "client_secret": secret,
        "grant_type": "client_credentials",
    }).encode()
    req = urllib.request.Request(TWITCH_TOKEN_URL, data=body,
                                 headers={"User-Agent": "gametime/1.0"})
    with urllib.request.urlopen(req, timeout=15) as resp:
        d = json.load(resp)
    token = {"access_token": d["access_token"],
             "expires_at": time.time() + d.get("expires_in", 0)}
    try:
        TOKEN_CACHE.write_text(json.dumps(token))
    except OSError:
        pass
    return token["access_token"]


def get_token(force_new=False):
    cid, secret = read_credentials()
    if not force_new and TOKEN_CACHE.exists():
        try:
            cached = json.loads(TOKEN_CACHE.read_text())
            # renew a week early so a token never dies mid-session
            if cached.get("expires_at", 0) - time.time() > 7 * 86400:
                return cached["access_token"]
        except (json.JSONDecodeError, OSError):
            pass
    return fetch_token(cid, secret)


def igdb_post(endpoint, body, _retried=False):
    cid, _ = read_credentials()
    req = urllib.request.Request(
        f"{IGDB_API}/{endpoint}",
        data=body.encode(),
        headers={"User-Agent": "gametime/1.0",
                 "Client-ID": cid,
                 "Authorization": f"Bearer {get_token(force_new=_retried)}"})
    try:
        with urllib.request.urlopen(req, timeout=20) as resp:
            return json.load(resp)
    except urllib.error.HTTPError as e:
        if e.code == 401 and not _retried:  # stale token: refresh once and retry
            return igdb_post(endpoint, body, _retried=True)
        sys.exit(f"IGDB error {e.code} on /{endpoint}: {e.read().decode(errors='replace')[:300]}")


# ---------- IGDB queries ----------

def trim_genres(names):
    return [GENRE_TRIM.get(n, n) for n in names]


def search_igdb(query, year=None):
    """Return candidate dicts with everything an entry needs (except TTB)."""
    q = query.replace('\\', '').replace('"', '\\"')
    data = igdb_post("games",
                     f'search "{q}"; '
                     f'fields name, first_release_date, genres.name, platforms.abbreviation, '
                     f'summary, cover.image_id, total_rating_count; limit 25;')
    out = []
    for r in data:
        ts = r.get("first_release_date")
        ryear = datetime.datetime.fromtimestamp(ts, datetime.timezone.utc).year if ts else None
        if year is not None and ryear != year:
            continue
        out.append({
            "igdb_id": r["id"],
            "title": r.get("name", "?"),
            "year": ryear,
            "genres": trim_genres([g["name"] for g in r.get("genres", [])]),
            "platforms": [p["abbreviation"] for p in r.get("platforms", [])
                          if p.get("abbreviation")],
            "overview": r.get("summary") or "",
            "cover_image_id": (r.get("cover") or {}).get("image_id"),
            "rating_count": r.get("total_rating_count") or 0,
        })
    return out


def pick_result(results, first=False):
    if not results:
        sys.exit("no IGDB results found (try a different spelling).")
    if first:
        # scripting escape hatch — take the best-known match without asking
        return max(results, key=lambda r: r["rating_count"])
    # always show the full list, big or small, best-known first — you pick
    results = sorted(results, key=lambda r: -r["rating_count"])
    print(f"\n{len(results)} match(es):")
    for i, r in enumerate(results, 1):
        year = r["year"] or "????"
        plats = ", ".join(r["platforms"][:5]) or "?"
        blurb = (r["overview"][:58] + "…") if len(r["overview"]) > 58 else r["overview"]
        print(f"  {i:2}. {r['title']} ({year})  [{plats}]  {blurb}")
    while True:
        choice = input("pick a number (or q to abort): ").strip()
        if choice.lower() == "q":
            sys.exit("aborted.")
        if choice.isdigit() and 1 <= int(choice) <= len(results):
            return results[int(choice) - 1]


def fetch_ttb(igdb_id):
    """Time-to-beat hours {hastily, normally, completely, samples} or None."""
    data = igdb_post("game_time_to_beats",
                     f"fields hastily, normally, completely, count; "
                     f"where game_id = {igdb_id};")
    if not data:
        return None
    d = data[0]
    # IGDB times are crowd-sourced; joke submissions occasionally slip in
    # (e.g. a 21,614-hour "main story") — drop anything past 1000h as noise
    hours = lambda s: round(s / 3600, 1) if s and s / 3600 <= 1000 else None
    ttb = {"hastily": hours(d.get("hastily")),
           "normally": hours(d.get("normally")),
           "completely": hours(d.get("completely")),
           "samples": d.get("count", 0)}
    return ttb if any(v for k, v in ttb.items() if k != "samples") else None


def download_cover(image_id, slug):
    if not image_id:
        print("no cover on IGDB — keeping pixel placeholder.")
        return None
    COVERS_DIR.mkdir(exist_ok=True)
    dest = COVERS_DIR / f"{slug}.jpg"
    req = urllib.request.Request(f"{IGDB_IMG}/{image_id}.jpg",
                                 headers={"User-Agent": "gametime/1.0"})
    with urllib.request.urlopen(req, timeout=30) as resp:
        dest.write_bytes(resp.read())
    print(f"cover -> covers/{slug}.jpg")
    return f"covers/{slug}.jpg"


# ---------- field parsing ----------

def parse_progress(text):
    """'12.5' or '12.5h' -> {hours: 12.5}"""
    m = re.fullmatch(r"(\d+(?:\.\d+)?)\s*h?", text.strip().lower())
    if not m:
        sys.exit("bad --progress format, expected hours played e.g. 12.5")
    return {"hours": float(m[1])}


def today():
    return datetime.date.today().isoformat()


# ---------- duplicate detection ----------

def normalize_title(title):
    return re.sub(r"[^a-z0-9]+", " ", title.lower()).strip()


def find_duplicates(lib, igdb_id, title):
    """Split a collision two ways.

    hard = the same IGDB game is already here — a genuine re-add, worth blocking.
    soft = a DIFFERENT game that merely shares the name (Resident Evil 4 2005 vs
           the 2023 remake). Perfectly legitimate, so only worth mentioning.

    igdbId is the identity; the title is just a label.
    """
    norm = normalize_title(title)
    hard = [e for e in lib if igdb_id is not None and e.get("igdbId") == igdb_id]
    hard_ids = {e["id"] for e in hard}
    soft = [e for e in lib
            if e["id"] not in hard_ids and normalize_title(e["title"]) == norm]
    return hard, soft


def confirm_duplicate(dupes, interactive):
    print("\nthis exact game is already in the library:")
    for e in dupes:
        print(f"  [{e['id']}] {e['title']} ({e.get('year', '?')}) — {e['status']}"
              f"  (igdbId {e.get('igdbId')})")
    print("to change an existing entry:  ./gametime.py update <id> ...")
    if not interactive:
        print("refusing to add the same game twice (pass --again to override).")
        return False
    ans = input("add it anyway? [y/N]: ").strip().lower()
    return ans in ("y", "yes")


def library_duplicates(lib):
    """(hard, soft) groups — hard share an IGDB id (the same game twice, a real
    problem), soft merely share a name (two different games, nothing to fix)."""
    by_igdb, by_title = {}, {}
    for e in lib:
        if e.get("igdbId") is not None:
            by_igdb.setdefault(e["igdbId"], []).append(e)
        by_title.setdefault(normalize_title(e["title"]), []).append(e)
    hard = [g for g in by_igdb.values() if len(g) > 1]
    hard_ids = {e["id"] for g in hard for e in g}
    soft = [g for g in by_title.values()
            if len(g) > 1 and not {e["id"] for e in g} <= hard_ids]
    return hard, soft


# ---------- commands ----------

def cmd_add(args):
    lib = load_library()
    if args.status is None:
        # a score means you've beaten (or shelved) it; otherwise it's backlog
        args.status = "played" if args.score is not None else "toplay"
    results = search_igdb(args.title, year=args.year)
    chosen = pick_result(results, first=args.first)
    hard, soft = find_duplicates(lib, chosen["igdb_id"], chosen["title"])
    if hard and not args.again:
        if not confirm_duplicate(hard, interactive=not args.first):
            sys.exit(1)
    slug = unique_slug(lib, chosen["title"], chosen["year"])
    if soft:
        print("\nnote: library already has a different game by this name:")
        for e in soft:
            print(f"  [{e['id']}] {e['title']} ({e.get('year', '?')}) — {e['status']}")
        print(f"adding as [{slug}]")
    cover = download_cover(chosen["cover_image_id"], slug)
    ttb = fetch_ttb(chosen["igdb_id"])
    if ttb:
        fmt = lambda v: f"{v}h" if v else "?"
        print(f"time to beat: {fmt(ttb['hastily'])} rush / {fmt(ttb['normally'])} main / "
              f"{fmt(ttb['completely'])} 100%  ({ttb['samples']} submissions)")
    else:
        print("no time-to-beat data on IGDB for this one.")

    entry = {
        "id": slug,
        "title": chosen["title"],
        "status": args.status,
        "year": chosen["year"],
        "genres": chosen["genres"] or ["Unknown"],
        "platforms": chosen["platforms"],
        "score": args.score,
        "synopsis": chosen["overview"],
        "date": args.date or today(),
        "cover": cover,
        "igdbId": chosen["igdb_id"],
        "ttb": ttb,
    }
    if args.notes:
        entry["notes"] = args.notes
    if args.progress:
        entry["progress"] = parse_progress(args.progress)

    lib.append(entry)
    save_library(lib)
    print(f"added: {entry['title']} ({entry['year']}) [{entry['id']}] as {entry['status']}")


def cmd_update(args):
    lib = load_library()
    e = find_entry(lib, args.id, args.year)
    if args.score is not None:
        e["score"] = args.score
        # scoring something means you've played it through (unless told otherwise)
        if not args.status and e["status"] != "played":
            args.status = "played"
    if args.status:
        if args.status == "played" and e["status"] != "played" and not args.date:
            e["date"] = today()  # finished today
        e["status"] = args.status
        if args.status != "playing":
            e.pop("progress", None)
    if args.date:
        e["date"] = args.date
    if args.notes is not None:
        if args.notes:
            e["notes"] = args.notes
        else:
            e.pop("notes", None)
    if args.progress:
        e["progress"] = parse_progress(args.progress)
    save_library(lib)
    print(f"updated: {e['title']} [{e['id']}]")


def cmd_remove(args):
    lib = load_library()
    e = find_entry(lib, args.id, args.year)
    lib.remove(e)
    cover = e.get("cover")
    if cover and (ROOT / cover).exists() and not args.keep_cover:
        (ROOT / cover).unlink()
        print(f"deleted {cover}")
    save_library(lib)
    print(f"removed: {e['title']} [{e['id']}]")


def cmd_list(args):
    lib = load_library()
    order = {"playing": 0, "toplay": 1, "played": 2}
    for e in sorted(lib, key=lambda x: (order.get(x["status"], 9), x["title"])):
        score = f"{e['score']:>4}" if e.get("score") is not None else "  — "
        ttb = e.get("ttb") or {}
        length = f"  ~{ttb['normally']}h" if ttb.get("normally") else ""
        prog = ""
        if e.get("progress"):
            prog = f"  @{e['progress']['hours']}h"
        print(f"{e['status']:8} {score}  {e['title']} ({e.get('year','?')}) [{e['id']}]{length}{prog}")
    print(f"\n{len(lib)} entries")


def cmd_regen(args):
    save_library(load_library())


def cmd_covers(args):
    """Re-download every cover at the current quality tier."""
    lib = load_library()
    ids = [e["igdbId"] for e in lib if e.get("igdbId")]
    if not ids:
        sys.exit("no entries with an IGDB id.")
    data = igdb_post("covers",
                     f"fields image_id, game; "
                     f"where game = ({','.join(map(str, ids))}); limit {len(ids)};")
    by_game = {d["game"]: d.get("image_id") for d in data}
    for e in lib:
        img = by_game.get(e.get("igdbId"))
        if img:
            e["cover"] = download_cover(img, e["id"])
    save_library(lib)


def cmd_check(args):
    lib = load_library()
    hard, soft = library_duplicates(lib)

    def show(group):
        for e in group:
            print(f"  [{e['id']}] {e['title']} ({e.get('year', '?')}) "
                  f"— {e['status']}, igdbId={e.get('igdbId')}")

    if soft:
        print(f"{len(soft)} shared name(s) — different games, nothing to fix:\n")
        for g in soft:
            show(g)
            print()
    if not hard:
        print(f"no duplicates found in {len(lib)} entries.")
        return
    print(f"{len(hard)} duplicate group(s) — the same game added twice:\n")
    for g in hard:
        show(g)
        print("  keep one, remove the rest:  ./gametime.py remove <id>\n")
    sys.exit(1)


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)

    a = sub.add_parser("add", help="look up a game on IGDB and add it")
    a.add_argument("title")
    a.add_argument("--year", type=int, help="only match this release year (disambiguates remakes)")
    a.add_argument("--status", choices=["playing", "toplay", "played"],
                   help="default: toplay, or played when --score is given")
    a.add_argument("--score", type=float, help="0–10, shown as pixel hearts")
    a.add_argument("--notes")
    a.add_argument("--progress", help="hours played so far, e.g. 12.5")
    a.add_argument("--date", help="YYYY-MM-DD (default: today)")
    a.add_argument("--first", action="store_true",
                   help="take the best-known result, don't ask")
    a.add_argument("--again", action="store_true",
                   help="allow adding a title already in the library")
    a.set_defaults(fn=cmd_add)

    u = sub.add_parser("update", help="change score/status/progress/notes of an entry")
    u.add_argument("id", help="entry id or title fragment")
    u.add_argument("--year", type=int, help="only match an entry from this year "
                                            "(picks between same-named games)")
    u.add_argument("--score", type=float)
    u.add_argument("--status", choices=["playing", "toplay", "played"])
    u.add_argument("--notes", help="new notes ('' to clear)")
    u.add_argument("--progress", help="hours played so far, e.g. 12.5")
    u.add_argument("--date", help="YYYY-MM-DD")
    u.set_defaults(fn=cmd_update)

    r = sub.add_parser("remove", help="delete an entry (and its cover)")
    r.add_argument("id", help="entry id or title fragment")
    r.add_argument("--year", type=int, help="only match an entry from this year "
                                            "(picks between same-named games)")
    r.add_argument("--keep-cover", action="store_true")
    r.set_defaults(fn=cmd_remove)

    sub.add_parser("list", help="print the library").set_defaults(fn=cmd_list)
    sub.add_parser("regen", help="rebuild data.js from library.json").set_defaults(fn=cmd_regen)
    sub.add_parser("covers", help="re-download all covers at current quality").set_defaults(fn=cmd_covers)
    sub.add_parser("check", help="scan the library for duplicate entries").set_defaults(fn=cmd_check)

    args = ap.parse_args()
    args.fn(args)


if __name__ == "__main__":
    main()
